import type { CatalogFile } from './types.js'

/** 离线兜底目录：接口未配置或不可用时使用，字段与在线契约完全一致。 */
export const offlineCatalog: CatalogFile = {
  version: '2026-10-04',
  updatedAt: '2026-10-04',
  resources: [
    {
      id: 'res-101',
      title: '探索辅助工具',
      kind: '修改器',
      gameName: '星陨边境',
      gameAliases: ['星陨', 'Starfall Frontier'],
      version: '1.4.2',
      compatibleVersion: '星陨边境 1.4.2',
      gameVersion: '1.4.2',
      source: '已验证作者页',
      status: '可用',
      updatedAt: '2026-09-26',
      description: '单机模式使用的修改器，仅用于本地演示与资源匹配流程验证。',
      tags: ['单机', '版本匹配'],
      risk: '中',
      downloadUrl: '',
      fileName: 'starfall-trainer-1.4.2.zip',
      homepage: '',
    },
    {
      id: 'res-102',
      title: '第一章起始存档',
      kind: '存档',
      gameName: '星陨边境',
      gameAliases: ['星陨', 'Starfall Frontier'],
      version: '1.4.2',
      compatibleVersion: '星陨边境 1.4.x',
      gameVersion: '1.4.2',
      source: '演示资源库',
      status: '可用',
      updatedAt: '2026-09-24',
      description: '包含分支节点说明，导入时会先建立本地备份。',
      tags: ['章节节点', '备份恢复'],
      risk: '低',
      downloadUrl: '',
      fileName: 'starfall-chapter1-save.zip',
      homepage: '',
    },
    {
      id: 'res-103',
      title: '极简界面 MOD',
      kind: 'MOD',
      gameName: '星陨边境',
      gameAliases: ['星陨', 'Starfall Frontier'],
      version: '1.1.0',
      compatibleVersion: '星陨边境 1.4.2',
      gameVersion: '1.4.2',
      source: '已验证作者页',
      status: '可用',
      updatedAt: '2026-09-22',
      description: '支持启停、安装计划预览与冲突检测。',
      tags: ['界面', '配置档案'],
      risk: '低',
      downloadUrl: '',
      fileName: 'starfall-minimal-ui-1.1.0.zip',
      homepage: '',
    },
    {
      id: 'res-104',
      title: '中文文本修复补丁',
      kind: '补丁',
      gameName: '深港纪事',
      gameAliases: ['深港', 'Deep Harbor'],
      version: '2.1.0',
      compatibleVersion: '深港纪事 2.1.0',
      gameVersion: '2.1.0',
      source: '官方合作页面',
      status: '可用',
      updatedAt: '2026-09-25',
      description: '用于演示补丁安装状态、版本校验与还原路径。',
      tags: ['汉化', '可还原'],
      risk: '低',
      downloadUrl: '',
      fileName: 'deep-harbor-zh-fix-2.1.0.zip',
      homepage: '',
    },
    {
      id: 'res-105',
      title: '舰队编队预设 MOD',
      kind: 'MOD',
      gameName: '轨道远征',
      gameAliases: ['轨道', 'Orbit Expedition'],
      version: '0.8.0',
      compatibleVersion: '轨道远征 0.9.7',
      gameVersion: '0.9.8',
      source: '待复核来源',
      status: '待核实',
      updatedAt: '2026-09-18',
      description: '资源版本与当前游戏版本不一致，默认提示风险。',
      tags: ['待核实', '版本差异'],
      risk: '中',
      downloadUrl: '',
      fileName: 'orbit-fleet-preset-0.8.0.zip',
      homepage: '',
    },
  ],
}
